components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100
        name:
          type: string
          example: CASEKOO iPhone Case 
        price:
          type: number
          format: double
          example: 24.00